version: 2

multi-ecosystem-groups:
  cicd:
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore:"
  development:
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore:"

updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: "chore:"
  groups:
    version:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
      # major updates will have their own PR
    security:
      applies-to: security-updates
      update-types:
      - "minor"
      - "patch"
      # major updates will have their own PR
- package-ecosystem: docker
  directory: "/"
  patterns: ["*"]
  multi-ecosystem-group: cicd
- package-ecosystem: github-actions
  directory: "/"
  patterns: ["*"]
  multi-ecosystem-group: cicd
- package-ecosystem: docker-compose
  directory: "/"
  patterns: ["*"]
  multi-ecosystem-group: development
- package-ecosystem: devcontainers
  directory: "/"
  patterns: ["*"]
  multi-ecosystem-group: development
