version: "2"

run:
  concurrency: 4
  timeout: 5m
  relative-path-mode: gomod
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true
output:
  path-prefix: ''

formatters:
  enable:
  - goimports
  - gofumpt
  - golines
linters:
  default: none
  enable:
  - govet
  - staticcheck
  - errcheck
  - unused
  - ineffassign
  # nondefault linters
  - nestif
  - errname
  - funlen
  - gocognit
  - goconst
  - lll
  - nolintlint
  - whitespace
  - unconvert
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false

severity:
  default: error
