version: "2"

run:
  concurrency: 4
  timeout: 5m
  relative-path-mode: gomod
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true
output:
  path-prefix: ''

linters:
  default: standard

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false

severity:
  default: error
