extends: default

rules:
  document-start:
    present: false
  indentation:
    spaces: 2
    indent-sequences: false
  line-length:
    max: 120
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
