application:
  shutdownTimeout: 10s

openai:
  systemPrompt: |
    You are a helpful assistant. Answer the user's questions to the best of your ability.
  api:
    endpoint:

http:
  listenAddr: ":8080"

xmpp:
  connectionTimeout: 10s

logger:
  level: debug
  timeKey: time
  format: logfmt
