name: Check Code

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  GO_VERSION: 1.23

jobs:
  super-lint:
    runs-on: ubuntu-latest
    if: false
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        persist-credentials: false
    - uses: super-linter/super-linter@v8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint-golang:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1
  lint-markdown:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v5
    - uses: DavidAnson/markdownlint-cli2-action@v20
      with:
        globs: '**/*.md'
  lint-yaml:
    runs-on: ubuntu-latest  # comes with yamllint pre-installed
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v5
    - run: yamllint -f github .
