name: Create Release

on: 
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
    - uses: CSchoel/release-notes-from-changelog@v1
    - uses: ncipollo/release-action@v1
      with:
        bodyFile: RELEASE.md